-- Forward-only hardening for the daily user_id schema generated by Lovable.
-- Existing accounts and business records are retained. Review before deploying.
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'timesheets' AND column_name = 'work_date') THEN
    RAISE EXCEPTION 'Expected the Lovable daily-timesheet schema. Migrate legacy employee/month records separately first.';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.is_active_user(_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$ SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = _user_id AND status = 'active'); $$;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles r JOIN public.profiles p ON p.id = r.user_id
    WHERE r.user_id = _user_id AND r.role = _role AND p.status = 'active'
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin_or_manager(_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT public.has_role(_user_id, 'admin') OR public.has_role(_user_id, 'manager');
$$;

REVOKE ALL ON FUNCTION public.is_active_user(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_admin_or_manager(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_active_user(uuid), public.has_role(uuid, public.app_role),
  public.is_admin_or_manager(uuid) TO authenticated, service_role;

-- Invite-only provisioning. Never promote a first registrant.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NEW.invited_at IS NULL THEN
    RAISE EXCEPTION 'Accounts are invite-only. Ask your administrator for an invitation.';
  END IF;
  INSERT INTO public.profiles (id, email, full_name)
  VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''));
  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'employee');
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

-- Security-critical changes are logged by the database, not forged by the client.
DROP POLICY IF EXISTS "Authenticated can insert own audit entries" ON public.audit_logs;
REVOKE INSERT, UPDATE, DELETE ON public.audit_logs FROM authenticated, anon;
CREATE OR REPLACE FUNCTION public.log_cloud_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.audit_logs (user_id, action, entity_type, entity_id, details)
  VALUES (auth.uid(), TG_OP, TG_TABLE_NAME, COALESCE(NEW.id, OLD.id)::text,
    jsonb_build_object('previous_status', CASE WHEN TG_OP = 'UPDATE' THEN to_jsonb(OLD)->>'status' END,
      'status', to_jsonb(NEW)->>'status'));
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.log_cloud_change() FROM PUBLIC, anon, authenticated;

-- Role assignments use a guarded RPC. Direct role-table mutation is forbidden.
REVOKE INSERT, UPDATE, DELETE ON public.user_roles FROM authenticated, anon;
CREATE OR REPLACE FUNCTION public.set_user_role(_user_id uuid, _role public.app_role)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('cloud-role-assignment', 0));
  IF NOT public.has_role(auth.uid(), 'admin') THEN RAISE EXCEPTION 'Administrator access required'; END IF;
  IF auth.uid() = _user_id THEN RAISE EXCEPTION 'You cannot change your own role'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = _user_id) THEN RAISE EXCEPTION 'Account not found'; END IF;
  IF _role <> 'admin' AND public.has_role(_user_id, 'admin') AND
      (SELECT count(*) FROM public.user_roles r JOIN public.profiles p ON p.id = r.user_id
       WHERE r.role = 'admin' AND p.status = 'active') <= 1 THEN
    RAISE EXCEPTION 'The last active administrator cannot be removed';
  END IF;
  DELETE FROM public.user_roles WHERE user_id = _user_id;
  INSERT INTO public.user_roles(user_id, role) VALUES (_user_id, _role);
  INSERT INTO public.audit_logs(user_id, action, entity_type, entity_id, details)
  VALUES (auth.uid(), 'SET_ROLE', 'user_roles', _user_id::text, jsonb_build_object('role', _role));
END;
$$;
REVOKE ALL ON FUNCTION public.set_user_role(uuid, public.app_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_user_role(uuid, public.app_role) TO authenticated;

-- Employees may edit contact details, not identities, roles or employment status.
REVOKE INSERT, DELETE ON public.profiles FROM authenticated, anon;
CREATE OR REPLACE FUNCTION public.guard_profile_update()
RETURNS trigger LANGUAGE plpgsql SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL AND current_user IN ('postgres', 'service_role', 'supabase_admin') THEN RETURN NEW; END IF;
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    PERFORM pg_advisory_xact_lock(hashtextextended('cloud-role-assignment', 0));
  END IF;
  IF NOT public.is_active_user(auth.uid()) THEN RAISE EXCEPTION 'Active account required'; END IF;
  IF NEW.id IS DISTINCT FROM OLD.id OR NEW.email IS DISTINCT FROM OLD.email OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'Authentication identity fields cannot be changed here';
  END IF;
  IF NOT public.has_role(auth.uid(), 'admin') AND
      (NEW.status IS DISTINCT FROM OLD.status OR NEW.department IS DISTINCT FROM OLD.department OR
       NEW.position IS DISTINCT FROM OLD.position OR NEW.employee_code IS DISTINCT FROM OLD.employee_code) THEN
    RAISE EXCEPTION 'Only an administrator may change employment details';
  END IF;
  IF btrim(NEW.full_name) = '' OR length(NEW.full_name) > 120 OR
      length(NEW.department) > 120 OR length(NEW.position) > 120 OR length(NEW.phone) > 40 THEN
    RAISE EXCEPTION 'Profile fields exceed their allowed length';
  END IF;
  IF NEW.status <> 'active' AND public.has_role(OLD.id, 'admin') AND
      (SELECT count(*) FROM public.user_roles r JOIN public.profiles p ON p.id = r.user_id
       WHERE r.role = 'admin' AND p.status = 'active') <= 1 THEN
    RAISE EXCEPTION 'The last active administrator cannot be deactivated';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER guard_cloud_profile BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.guard_profile_update();

-- Replace permissive policies, including immutable pending/approved work content.
DROP POLICY "Employees insert own" ON public.timesheets;
DROP POLICY "Employees update own pending; admins/managers any" ON public.timesheets;
DROP POLICY "Employees delete own pending; admins any" ON public.timesheets;
DROP POLICY "View own or all if admin/manager" ON public.timesheets;
CREATE POLICY "Cloud timesheets select" ON public.timesheets FOR SELECT TO authenticated
  USING (public.is_active_user(auth.uid()) AND (user_id = auth.uid() OR public.is_admin_or_manager(auth.uid())));
CREATE POLICY "Cloud timesheets insert" ON public.timesheets FOR INSERT TO authenticated
  WITH CHECK (public.is_active_user(auth.uid()) AND user_id = auth.uid() AND status IN ('draft', 'pending')
    AND approved_by IS NULL AND approved_at IS NULL AND rejection_reason IS NULL);
CREATE POLICY "Cloud timesheets update" ON public.timesheets FOR UPDATE TO authenticated
  USING (public.is_active_user(auth.uid()) AND (
    (user_id = auth.uid() AND status IN ('draft', 'rejected')) OR
    (user_id <> auth.uid() AND status = 'pending' AND public.is_admin_or_manager(auth.uid()))))
  WITH CHECK (public.is_active_user(auth.uid()) AND (
    (user_id = auth.uid() AND status IN ('draft', 'pending')) OR
    (user_id <> auth.uid() AND status IN ('approved', 'rejected') AND public.is_admin_or_manager(auth.uid()))));
REVOKE DELETE ON public.timesheets FROM authenticated, anon;

CREATE OR REPLACE FUNCTION public.guard_timesheet()
RETURNS trigger LANGUAGE plpgsql SET search_path = public
AS $$
DECLARE
  work_minutes integer;
  ot_minutes integer := 0;
  ot_offset integer;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.id IS DISTINCT FROM OLD.id OR NEW.user_id IS DISTINCT FROM OLD.user_id OR
       NEW.work_date IS DISTINCT FROM OLD.work_date OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
      RAISE EXCEPTION 'Timesheet identity and date are immutable';
    END IF;
    IF OLD.status = 'approved' THEN RAISE EXCEPTION 'Approved time entries are locked'; END IF;
    IF NEW.user_id <> auth.uid() AND auth.uid() IS NOT NULL THEN
      IF NOT public.is_admin_or_manager(auth.uid()) OR OLD.status <> 'pending' OR NEW.status NOT IN ('approved', 'rejected') THEN
        RAISE EXCEPTION 'Only a manager may review pending entries';
      END IF;
      IF NEW.start_time IS DISTINCT FROM OLD.start_time OR NEW.end_time IS DISTINCT FROM OLD.end_time OR
         NEW.break_minutes IS DISTINCT FROM OLD.break_minutes OR NEW.ot_start IS DISTINCT FROM OLD.ot_start OR
         NEW.ot_end IS DISTINCT FROM OLD.ot_end OR NEW.description IS DISTINCT FROM OLD.description THEN
        RAISE EXCEPTION 'Review cannot change submitted work content';
      END IF;
    ELSIF auth.uid() IS NOT NULL AND (OLD.status NOT IN ('draft', 'rejected') OR NEW.status NOT IN ('draft', 'pending')) THEN
      RAISE EXCEPTION 'Only draft or rejected entries may be resubmitted';
    END IF;
  END IF;
  IF auth.uid() IS NOT NULL AND NEW.user_id = auth.uid() AND NEW.status IN ('approved', 'rejected') THEN
    RAISE EXCEPTION 'Self-approval and self-rejection are not allowed';
  END IF;
  IF NEW.start_time IS NULL OR NEW.end_time IS NULL OR NEW.start_time = NEW.end_time THEN
    RAISE EXCEPTION 'Provide a nonzero regular work interval';
  END IF;
  IF NEW.start_time >= time '24:00' OR NEW.end_time >= time '24:00' OR
      EXTRACT(second FROM NEW.start_time) <> 0 OR EXTRACT(second FROM NEW.end_time) <> 0 THEN
    RAISE EXCEPTION 'Use minute-precision times from 00:00 to 23:59';
  END IF;
  work_minutes := mod((EXTRACT(epoch FROM (NEW.end_time - NEW.start_time)) / 60)::integer + 1440, 1440);
  IF NEW.break_minutes < 0 OR NEW.break_minutes >= work_minutes THEN RAISE EXCEPTION 'Invalid break duration'; END IF;
  IF (NEW.ot_start IS NULL) <> (NEW.ot_end IS NULL) THEN RAISE EXCEPTION 'Provide both overtime times'; END IF;
  IF NEW.ot_start IS NOT NULL THEN
    IF NEW.ot_start >= time '24:00' OR NEW.ot_end >= time '24:00' OR
        EXTRACT(second FROM NEW.ot_start) <> 0 OR EXTRACT(second FROM NEW.ot_end) <> 0 THEN
      RAISE EXCEPTION 'Use minute-precision overtime times';
    END IF;
    ot_minutes := mod((EXTRACT(epoch FROM (NEW.ot_end - NEW.ot_start)) / 60)::integer + 1440, 1440);
    ot_offset := mod((EXTRACT(epoch FROM (NEW.ot_start - NEW.start_time)) / 60)::integer + 1440, 1440);
    IF ot_minutes = 0 OR ot_offset < work_minutes OR ot_offset + ot_minutes > 1440 THEN
      RAISE EXCEPTION 'Overtime overlaps regular work or extends beyond a 24-hour shift';
    END IF;
  END IF;
  IF length(NEW.description) > 2000 THEN RAISE EXCEPTION 'Description is too long'; END IF;
  NEW.total_hours := round((work_minutes - NEW.break_minutes + ot_minutes)::numeric / 60, 2);
  IF NEW.status = 'approved' THEN
    NEW.approved_by := auth.uid();
    NEW.approved_at := now();
    NEW.rejection_reason := NULL;
  ELSIF NEW.status = 'rejected' THEN
    IF btrim(COALESCE(NEW.rejection_reason, '')) = '' OR length(NEW.rejection_reason) > 2000 THEN
      RAISE EXCEPTION 'A rejection reason of 1-2000 characters is required';
    END IF;
    NEW.approved_by := NULL; NEW.approved_at := NULL;
  ELSE
    NEW.approved_by := NULL; NEW.approved_at := NULL; NEW.rejection_reason := NULL;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER guard_cloud_timesheet BEFORE INSERT OR UPDATE ON public.timesheets
  FOR EACH ROW EXECUTE FUNCTION public.guard_timesheet();
CREATE TRIGGER audit_cloud_timesheet AFTER INSERT OR UPDATE ON public.timesheets
  FOR EACH ROW EXECUTE FUNCTION public.log_cloud_change();

DROP POLICY "Employees insert own leave" ON public.leave_applications;
DROP POLICY "Update own pending or admin/manager any" ON public.leave_applications;
DROP POLICY "Delete own pending or admin any" ON public.leave_applications;
DROP POLICY "View own leaves or all if admin/manager" ON public.leave_applications;
CREATE POLICY "Cloud leave select" ON public.leave_applications FOR SELECT TO authenticated
  USING (public.is_active_user(auth.uid()) AND (user_id = auth.uid() OR public.is_admin_or_manager(auth.uid())));
CREATE POLICY "Cloud leave insert" ON public.leave_applications FOR INSERT TO authenticated
  WITH CHECK (public.is_active_user(auth.uid()) AND user_id = auth.uid() AND status = 'pending'
    AND approved_by IS NULL AND approved_at IS NULL AND rejection_reason IS NULL);
CREATE POLICY "Cloud leave review" ON public.leave_applications FOR UPDATE TO authenticated
  USING (public.is_admin_or_manager(auth.uid()) AND user_id <> auth.uid() AND status = 'pending')
  WITH CHECK (public.is_admin_or_manager(auth.uid()) AND user_id <> auth.uid() AND status IN ('approved', 'rejected'));
REVOKE DELETE ON public.leave_applications FROM authenticated, anon;

CREATE OR REPLACE FUNCTION public.guard_leave()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  y integer;
  entitlement numeric;
  used numeric;
  requested integer;
BEGIN
  IF auth.uid() IS NOT NULL AND TG_OP = 'INSERT' AND NEW.user_id <> auth.uid() THEN
    RAISE EXCEPTION 'You may only request leave for your own account';
  END IF;
  IF NEW.end_date < NEW.start_date OR NEW.end_date - NEW.start_date >= 366 THEN
    RAISE EXCEPTION 'Leave dates must cover 1-366 calendar days';
  END IF;
  IF btrim(COALESCE(NEW.reason, '')) = '' OR length(NEW.reason) > 2000 THEN RAISE EXCEPTION 'A reason of 1-2000 characters is required'; END IF;
  IF TG_OP = 'INSERT' AND NEW.status <> 'pending' THEN RAISE EXCEPTION 'New leave must be pending'; END IF;
  IF TG_OP = 'UPDATE' THEN
    IF OLD.status <> 'pending' OR NEW.status NOT IN ('approved', 'rejected') THEN RAISE EXCEPTION 'Only pending leave can be reviewed'; END IF;
    IF auth.uid() IS NOT NULL AND (NEW.user_id = auth.uid() OR NOT public.is_admin_or_manager(auth.uid())) THEN
      RAISE EXCEPTION 'Another manager must review leave';
    END IF;
    IF NEW.id IS DISTINCT FROM OLD.id OR NEW.user_id IS DISTINCT FROM OLD.user_id OR
        NEW.start_date IS DISTINCT FROM OLD.start_date OR NEW.end_date IS DISTINCT FROM OLD.end_date OR
        NEW.leave_type IS DISTINCT FROM OLD.leave_type OR NEW.reason IS DISTINCT FROM OLD.reason OR
        NEW.created_at IS DISTINCT FROM OLD.created_at THEN RAISE EXCEPTION 'Review cannot change leave content'; END IF;
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(NEW.user_id::text, 0));
  IF NEW.status IN ('pending', 'approved') AND EXISTS (
    SELECT 1 FROM public.leave_applications WHERE user_id = NEW.user_id AND id <> NEW.id
      AND status IN ('pending', 'approved') AND start_date <= NEW.end_date AND end_date >= NEW.start_date
  ) THEN RAISE EXCEPTION 'This leave overlaps an existing pending or approved request'; END IF;
  NEW.days := NEW.end_date - NEW.start_date + 1;
  IF NEW.status = 'approved' AND NEW.leave_type IN ('annual', 'sick', 'casual') THEN
    FOR y IN EXTRACT(year FROM NEW.start_date)::integer..EXTRACT(year FROM NEW.end_date)::integer LOOP
      -- The per-user lock serializes approvals. Entitlements are totals, not mutable remaining balances.
      SELECT CASE NEW.leave_type WHEN 'annual' THEN annual WHEN 'sick' THEN sick ELSE casual END
        INTO entitlement FROM public.leave_balances WHERE user_id = NEW.user_id AND year = y FOR UPDATE;
      IF entitlement IS NULL THEN RAISE EXCEPTION 'Configure leave entitlement for year % before approving', y; END IF;
      SELECT COALESCE(sum(GREATEST(0, LEAST(end_date, make_date(y,12,31)) - GREATEST(start_date, make_date(y,1,1)) + 1)), 0)
        INTO used FROM public.leave_applications WHERE user_id = NEW.user_id AND leave_type = NEW.leave_type
          AND status = 'approved' AND id <> NEW.id AND start_date <= make_date(y,12,31) AND end_date >= make_date(y,1,1);
      requested := LEAST(NEW.end_date, make_date(y,12,31)) - GREATEST(NEW.start_date, make_date(y,1,1)) + 1;
      IF used + requested > entitlement THEN RAISE EXCEPTION 'Insufficient % leave entitlement for year %', NEW.leave_type, y; END IF;
    END LOOP;
  END IF;
  IF NEW.status = 'approved' THEN NEW.approved_by := auth.uid(); NEW.approved_at := now(); NEW.rejection_reason := NULL;
  ELSIF NEW.status = 'rejected' THEN
    IF btrim(COALESCE(NEW.rejection_reason, '')) = '' OR length(NEW.rejection_reason) > 2000 THEN
      RAISE EXCEPTION 'A rejection reason of 1-2000 characters is required';
    END IF;
    NEW.approved_by := NULL; NEW.approved_at := NULL;
  ELSE NEW.approved_by := NULL; NEW.approved_at := NULL; NEW.rejection_reason := NULL;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER guard_cloud_leave BEFORE INSERT OR UPDATE ON public.leave_applications
  FOR EACH ROW EXECUTE FUNCTION public.guard_leave();
CREATE TRIGGER audit_cloud_leave AFTER INSERT OR UPDATE ON public.leave_applications
  FOR EACH ROW EXECUTE FUNCTION public.log_cloud_change();

ALTER TABLE public.leave_balances ADD CONSTRAINT cloud_leave_entitlement_limits
  CHECK (year BETWEEN 2020 AND 2100 AND annual BETWEEN 0 AND 366 AND sick BETWEEN 0 AND 366 AND casual BETWEEN 0 AND 366) NOT VALID;
CREATE TRIGGER audit_cloud_leave_balance AFTER INSERT OR UPDATE ON public.leave_balances
  FOR EACH ROW EXECUTE FUNCTION public.log_cloud_change();

REVOKE ALL ON FUNCTION public.guard_profile_update(), public.guard_timesheet(), public.guard_leave()
  FROM PUBLIC, anon, authenticated;

-- Timers are authoritative server-clock sessions, not editable browser counters.
CREATE TABLE public.work_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  work_date date NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  last_started_at timestamptz,
  finished_at timestamptz,
  elapsed_seconds integer NOT NULL DEFAULT 0 CHECK (elapsed_seconds >= 0),
  status text NOT NULL CHECK (status IN ('active', 'paused', 'completed')),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX one_open_work_session ON public.work_sessions(user_id) WHERE status IN ('active', 'paused');
CREATE INDEX cloud_sessions_user_date ON public.work_sessions(user_id, work_date DESC);
ALTER TABLE public.work_sessions ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.work_sessions TO authenticated;
GRANT ALL ON public.work_sessions TO service_role;
REVOKE INSERT, UPDATE, DELETE ON public.work_sessions FROM authenticated, anon;
CREATE POLICY "Cloud work sessions select" ON public.work_sessions FOR SELECT TO authenticated
  USING (public.is_active_user(auth.uid()) AND (user_id = auth.uid() OR public.is_admin_or_manager(auth.uid())));
CREATE TRIGGER audit_cloud_work_session AFTER INSERT OR UPDATE ON public.work_sessions
  FOR EACH ROW EXECUTE FUNCTION public.log_cloud_change();

CREATE OR REPLACE FUNCTION public.start_work_session(_work_date date)
RETURNS SETOF public.work_sessions LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE result public.work_sessions;
BEGIN
  IF NOT public.is_active_user(auth.uid()) THEN RAISE EXCEPTION 'Active account required'; END IF;
  IF _work_date IS NULL OR abs(_work_date - current_date) > 1 THEN RAISE EXCEPTION 'Start work for your current local date'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(auth.uid()::text, 0));
  IF EXISTS (SELECT 1 FROM public.work_sessions WHERE user_id = auth.uid() AND status IN ('active', 'paused')) THEN
    RAISE EXCEPTION 'A work session is already active or paused';
  END IF;
  INSERT INTO public.work_sessions(user_id, work_date, started_at, last_started_at, status)
  VALUES (auth.uid(), _work_date, clock_timestamp(), clock_timestamp(), 'active') RETURNING * INTO result;
  RETURN NEXT result;
END;
$$;

CREATE OR REPLACE FUNCTION public.transition_work_session(_id uuid, _action text, _expected_updated_at timestamptz)
RETURNS SETOF public.work_sessions LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE result public.work_sessions; stamp timestamptz;
BEGIN
  IF NOT public.is_active_user(auth.uid()) THEN RAISE EXCEPTION 'Active account required'; END IF;
  SELECT * INTO result FROM public.work_sessions WHERE id = _id AND user_id = auth.uid() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Work session not found'; END IF;
  IF result.updated_at IS DISTINCT FROM _expected_updated_at THEN RAISE EXCEPTION 'Session changed. Refresh and retry'; END IF;
  IF result.status = 'completed' OR _action NOT IN ('pause', 'resume', 'complete') OR _action IS NULL THEN
    RAISE EXCEPTION 'Invalid work session transition';
  END IF;
  IF (_action = 'pause' AND result.status <> 'active') OR (_action = 'resume' AND result.status <> 'paused') THEN
    RAISE EXCEPTION 'Invalid work session transition';
  END IF;
  stamp := clock_timestamp();
  IF result.status = 'active' THEN
    result.elapsed_seconds := result.elapsed_seconds + GREATEST(0, floor(EXTRACT(epoch FROM stamp - result.last_started_at)))::integer;
  END IF;
  result.status := CASE _action WHEN 'pause' THEN 'paused' WHEN 'resume' THEN 'active' ELSE 'completed' END;
  result.last_started_at := CASE WHEN _action = 'resume' THEN stamp ELSE NULL END;
  result.finished_at := CASE WHEN _action = 'complete' THEN stamp ELSE NULL END;
  UPDATE public.work_sessions SET status = result.status, elapsed_seconds = result.elapsed_seconds,
    last_started_at = result.last_started_at, finished_at = result.finished_at, updated_at = stamp
    WHERE id = _id RETURNING * INTO result;
  RETURN NEXT result;
END;
$$;
REVOKE ALL ON FUNCTION public.start_work_session(date), public.transition_work_session(uuid, text, timestamptz) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.start_work_session(date), public.transition_work_session(uuid, text, timestamptz) TO authenticated;

COMMIT;
